version: 3

env:
  VERSION: 1.21.5

tasks:
  install:
    cmds:
    - wget -nc https://go.dev/dl/go{{ .VERSION }}.linux-amd64.tar.gz -O go.tar.gz
    - defer: rm go.tar.gz
    - sudo tar -C /usr/local -xzf go.tar.gz
    - /usr/local/go/bin/go version
    - cowsay "Remember to reload shell"
    status:
    - go version | grep {{ .VERSION }}