version: 3

tasks:
  install:
    vars:
      VERSION: 1.22.0
    cmds:
    - wget -nc https://go.dev/dl/go{{ .VERSION }}.{{ OS }}-{{ ARCH }}.tar.gz -O go.tar.gz
    - defer: rm go.tar.gz
    - sudo tar -C /usr/local -xzf go.tar.gz
    - /usr/local/go/bin/go version
    - cowsay "Remember to reload shell"
    status:
    - /usr/local/go/bin/go version | grep {{ .VERSION }}