version: 3

tasks:
  copy:all:
  - task: copy:aliases
  - task: copy:zshrc
  - task: copy:p10k
  - task: copy:envrc

  copy:aliases:
  - cp .aliases ~/.aliases

  copy:zshrc:
  - cp .zshrc ~/.zshrc

  copy:p10k:
  - cp .p10k.zsh ~/.p10k.zsh

  copy:envrc:
  - cp .envrc ~/.envrc