version: 3

tasks:
  copy:all:
  - task: copy:aliases
  - task: copy:zshrc
  - task: copy:p10k
  - task: copy:envrc

  copy:aliases:
  - cp dotfiles/.aliases ~/.aliases

  copy:zshrc:
  - cp dotfiles/.zshrc ~/.zshrc

  copy:p10k:
  - cp dotfiles/.p10k.zsh ~/.p10k.zsh

  copy:envrc:
  - cp dotfiles/.envrc ~/.envrc