version: 3

vars:
  # -- Supported: nala | apt
  INSTALLER: nala

tasks:
  essentials:install:
  - task: kubectl:install
  - task: kubectl:plugins:install 
  - task: helm:install
  - task: helm:plugins:install
  - task: trivy:install

  paranoia:install:
    cmds:
    - sudo wget https://github.com/jetstack/paranoia/releases/download/v0.2.0/paranoia-linux-amd64 -O /usr/local/bin/paranoia
    - sudo chmod +x /usr/local/bin/paranoia
    status:
    - command -v paranoia 

  docker:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y docker-compose
    - task: docker:configure
    status:
    - command -v docker

  docker:configure:
    cmds:
    - sudo usermod -aG docker ${USER}

  kubectl:install:
    cmds:
    - arkade get kubectl
    status:
    - command -v kubectl

  kubectl:plugins:install:
    cmds:
    - arkade get krew
    - krew install switch-config
    - krew install ctx
    - krew install ns
    - krew install view-serviceaccount-kubeconfig
    - krew install assert
    - krew install view-secret
    status:
    - command -v krew
    - kubectl plugin list | grep ctx

  helm:install:
    cmds:
    - arkade get helm
    status:
    - command -v helm

  helm:plugins:install:
    cmds:
    - helm plugin install https://github.com/komodorio/helm-dashboard.git
    - helm plugin install https://github.com/jkroepke/helm-secrets
    status:
    - helm plugin list | grep secrets
    - helm plugin list | grep dashboard

  trivy:install:
    cmds:
    - arkade get trivy
    status:
    - command -v trivy