version: 3

vars:
  # -- Supported: nala | apt
  INSTALLER: nala

tasks:
  paranoia:install:
    cmds:
    - sudo wget https://github.com/jetstack/paranoia/releases/download/v0.2.0/paranoia-linux-amd64 -O /usr/local/bin/paranoia
    - sudo chmod +x /usr/local/bin/paranoia
    status:
    - command -v paranoia 

  docker:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y docker-compose
    - task: docker:configure
    status:
    - command -v docker

  docker:configure:
    cmds:
    - sudo usermod -aG docker ${USER}

  kubectl:install:
    cmds:
    - arkade get kubectl
    status:
    - command -v kubectl

  kubectl:plugins:install:
    cmds:
    - arkade get krew
    - krew install switch-config
    status:
    - arkade get krew
    - krew install switch-config