version: 3

vars:
  # -- Supported: nala | apt
  INSTALLER: nala

includes:
  portainer:
    dir: portainer
    taskfile: portainer/Taskfile.yaml

tasks:
  install:essentials:
  - task: docker:install
  - task: kubectl:install
  - task: kubectl:plugins:install 
  - task: helm:install
  - task: helm:plugins:install
  - task: trivy:install
  - task: lazydocker:install

  extras:install:
  - task: steampipe:install
  - task: steampipe:plugins:install

  paranoia:install:
    cmds:
    - sudo wget https://github.com/jetstack/paranoia/releases/download/v0.2.0/paranoia-linux-amd64 -O /usr/local/bin/paranoia
    - sudo chmod +x /usr/local/bin/paranoia
    status:
    - command -v paranoia 

  docker:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y docker-compose
    - task: docker:configure
    status:
    - command -v docker

  docker:configure:
    cmds:
    - sudo usermod -aG docker ${USER}

  kubectl:install:
    cmds:
    - arkade get kubectl
    status:
    - command -v kubectl

  kubectl:plugins:install:
    cmds:
    - arkade get krew
    - krew install switch-config
    - krew install ctx
    - krew install ns
    - krew install view-serviceaccount-kubeconfig
    - krew install assert
    - krew install view-secret
    status:
    - command -v krew
    - kubectl plugin list | grep ctx

  helm:install:
    cmds:
    - arkade get helm
    status:
    - command -v helm

  helm:plugins:install:
    cmds:
    - helm plugin install https://github.com/komodorio/helm-dashboard.git
    - helm plugin install https://github.com/jkroepke/helm-secrets
    status:
    - helm plugin list | grep secrets
    - helm plugin list | grep dashboard

  trivy:install:
    cmds:
    - arkade get trivy
    status:
    - command -v trivy

  steampipe:install:
    cmds:
    - sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
    status:
    - command -v steampipe
  
  steampipe:plugins:install:
    deps:
    - steampipe:install
    cmds:
    - steampipe plugin install kubernetes
    status:
    - steampipe plugin list | grep kubernetes

  steampipe:mods:install:
    deps:
    - steampipe:install
    cmds:
    - mkdir -p ~/.steampipe/mods
    - git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance ~/.steampipe/mods/kubernetes-compliance
    - git clone https://github.com/turbot/steampipe-mod-kubernetes-insights ~/.steampipe/mods/kubernetes-insights
    status:
    - test -d ~/.steampipe/mods/kubernetes-compliance
    - test -d ~/.steampipe/mods/kubernetes-insights

  steampipe:mod:kubernetes-compliance:
    dir: ~/.steampipe/mods/kubernetes-compliance
    deps:
    - steampipe:mods:install
    cmds: 
    - steampipe dashboard

  steampipe:mod:kubernetes-insights:
    dir: ~/.steampipe/mods/kubernetes-insights
    deps:
    - steampipe:mods:install 
    cmds:
    - steampipe dashboard


  lazytrivy:install:
    cmds:
    - wget -nc -O lazytrivy https://github.com/owenrumney/lazytrivy/releases/download/v1.0.2/lazytrivy-linux-amd64
    - chmod +x lazytrivy
    - sudo mv lazytrivy /usr/local/bin/lazytrivy
    status:
    - command -v lazytrivy

  lazydocker:install:
    cmds:
    - brew install lazydocker
    status:
    - command -v lazydocker

  velero:install:
    cmds:
    # - brew install velero
    - gh release download --repo vmware-tanzu/velero --skip-existing --pattern velero-*-{{ OS }}-{{ ARCH }}.tar.gz
    - defer: rm velero-*-{{ OS }}-{{ ARCH }}.tar.gz
    - tar -xvf velero-*-{{ OS }}-{{ ARCH }}.tar.gz
    - sudo mv velero-*-{{ OS }}-{{ ARCH }}/velero /usr/local/bin/velero
    - defer: rm -rf velero-*-{{ OS }}-{{ ARCH }}
    status:
    - command -v velero