version: 3

vars:
  STATUS_FILES_PATH: .taskfiles/statusfiles
  USER_STATUS_FILES_PATH: ~/.statusfiles

includes:
  zsh: zsh/Taskfile.yaml
  tools: .taskfiles/tools.yaml
  conky: apps/conky/Taskfile.yaml
  dotfiles: dotfiles/Taskfile.yaml
  server: .taskfiles/server.yaml
  system: .taskfiles/system.yaml
  git: .taskfiles/git.yaml
  footloose: 
    taskfile: tools/footloose/Taskfile.yaml
    dir: tools/footloose

tasks:
  default:
  - task: zsh:install-all

  list:
  - task -l

  argo-generate-password:
    cmds:
    - htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/' && echo 
    - echo $(date +%FT%T%Z)

# to test: webmin, usermin, cloudmin, virtualmin , virtualmind, cloudpanel, aapanel


