version: 3

# vars:
  # STATUS_FILES_PATH: .taskfiles/statusfiles
  # USER_STATUS_FILES_PATH: ~/.statusfiles

includes:
  package-manager: modules/package-manager/Taskfile.yaml
  upgrades: modules/upgrades/Taskfile.yaml
  zsh: 
    taskfile: modules/zsh/Taskfile.yaml
    dir: modules/zsh
  tools: modules/tools/Taskfile.yaml
  # conky: apps/conky/Taskfile.yaml
  # dotfiles: 
  #   taskfile: dotfiles/Taskfile.yaml
  #   dir: dotfiles
  # server: modules/server.yaml
  # system: modules/system.yaml
  git: 
    taskfile: modules/git/Taskfile.yaml
    # dir: modules/git
  dotfiles:
    taskfile: modules/dotfiles/Taskfile.yaml
    dir: modules/dotfiles
  containers: modules/containers/Taskfile.yaml
  # footloose: 
  #   taskfile: tools/footloose/Taskfile.yaml
  #   dir: tools/footloose
  coding: modules/coding/Taskfile.yaml
  server: modules/server.yaml
  vm: modules/vm/Taskfile.yaml

tasks:
  default:
  - task: zsh:install:all
  - task: dotfiles:copy:all
  - task: git:configure
  - task: package-manager:nix:install
  - task: package-manager:homebrew:install
  - task: tools:install:essentials
  - task: tools:install:desktop
  - task: upgrades:topgrade:install
  - task: containers:docker:install
  - task: containers:kubectl:install
  - task: containers:kubectl:plugins:install
  - task: containers:lazytrivy:install
  - task: upgrades:topgrade:install
  - task: tools:install:essentials
  - task: tools:install:desktop
  - task: containers:essentials:install

  - task: coding:vendir:install

  upgrade:
  - task: upgrades:topgrade:run

  # list:
  # - task -l

  # set:fix:
  # - task: zsh:copy:scripts
  # - task: git:copy:scripts
  # - task: dotfiles:copy:aliases
