version: 3

# vars:
  # STATUS_FILES_PATH: .taskfiles/statusfiles
  # USER_STATUS_FILES_PATH: ~/.statusfiles

includes:
  upgrades: modules/upgrades/Taskfile.yaml
  # zsh: 
  #   taskfile: modules/zsh/Taskfile.yaml
  #   dir: modules/zsh
  # tools: tools/Taskfile.yaml
  # conky: apps/conky/Taskfile.yaml
  # dotfiles: 
  #   taskfile: dotfiles/Taskfile.yaml
  #   dir: dotfiles
  # server: modules/server.yaml
  # system: modules/system.yaml
  # git: 
  #   taskfile: modules/git/Taskfile.yaml
  #   dir: modules/git
  # footloose: 
  #   taskfile: tools/footloose/Taskfile.yaml
  #   dir: tools/footloose

tasks:
  # default:
  # - task: git:pull
  # - task: zsh:install-all

  # list:
  # - task -l

  # set:fix:
  # - task: zsh:copy:scripts
  # - task: git:copy:scripts
  # - task: dotfiles:copy:aliases
