version: 3

# vars:
  # STATUS_FILES_PATH: .taskfiles/statusfiles
  # USER_STATUS_FILES_PATH: ~/.statusfiles

includes:
  apps: modules/apps/Taskfile.yaml
  package-manager: 
    taskfile: modules/package-manager/Taskfile.yaml
    dir: modules/package-manager
  zsh: 
    taskfile: modules/zsh/Taskfile.yaml
    dir: modules/zsh
  tools: modules/tools/Taskfile.yaml
  # conky: apps/conky/Taskfile.yaml
  # dotfiles: 
  #   taskfile: dotfiles/Taskfile.yaml
  #   dir: dotfiles
  # server: modules/server.yaml
  # system: modules/system.yaml
  git: 
    taskfile: modules/git/Taskfile.yaml
    # dir: modules/git
  dotfiles:
    taskfile: modules/dotfiles/Taskfile.yaml
    dir: modules/dotfiles
  containers: modules/containers/Taskfile.yaml
  # footloose: 
  #   taskfile: tools/footloose/Taskfile.yaml
  #   dir: tools/footloose
  coding: modules/coding/Taskfile.yaml
  server: modules/server.yaml
  vm: modules/vm/Taskfile.yaml
  kubernetes: modules/kubernetes/Taskfile.yaml
  vpn: modules/vpn/Taskfile.yaml
  collaboration: modules/collaboration/Taskfile.yaml
  ubuntu: profiles/ubuntu.yaml
  secrets: modules/secrets
  mirai: profiles/mirai.yaml
  macos: profiles/macos.yaml
  databases: modules/databases
  notifications: 
    taskfile: modules/notifications/Taskfile.yaml
    dir: modules/notifications
  management: modules/management
  aws: modules/aws
  networking: modules/networking

tasks:
  commit: 
  - git add .
  - git commit -m "commit"
  - git push origin main

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
    - pwd

  test2: pwd

  upgrade:
  - task: package-manager:topgrade:run

  fail: echo "Provide a profile"

  # list:
  # - task -l

  # set:fix:
  # - task: zsh:copy:scripts
  # - task: git:copy:scripts
  # - task: dotfiles:copy:aliases

  info:
    cmds:
    - |
      echo "OS: {{ OS }}"
    - |
      echo "ARCH: {{ ARCH }}"