version: 3

tasks:
  tailscale:install:
    cmds:
    - curl -fsSL https://tailscale.com/install.sh | sh
    status:
    - command -v tailscale

# For modprobe issues
# https://github.com/tailscale/tailscale/issues/825#issuecomment-775296495 
# https://dustri.org/b/running-tailscale-inside-of-a-proxmox-container.html 

  tailscale:start: 
    cmds:
    - sudo tailscale up --ssh
    status:
    - tailscale status
