version: 3

tasks:
  tailscale:install:
    cmds:
    - curl -fsSL https://tailscale.com/install.sh | sh
    status:
    - command -v tailscale

  tailscale:start: 
    cmds:
    - sudo tailscale up --ssh
    status:
    - sudo tailscale status
