version: 3

includes:
  devbox:
    taskfile: devbox/Taskfile.yaml
    dir: devbox
  vendir: vendir/Taskfile.yaml
  node: node/Taskfile.yaml
  go: go/Taskfile.yaml

tasks:
  install:d2:
    cmds:
    - curl -fsSL https://d2lang.com/install.sh | sh -s --
    status:
    - command -v d2

  install:essentials:
    deps:
    - install:d2