version: 3

tasks:
  create:data-dir:
    cmds:
    - sudo mkdir /portainer
    status:
      - test -d /portainer


  create:docker-compose:
    deps:
    - create:data-dir
    cmds:
    - docker-compose up -d 

  create:
  - docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

  start:
  - docker start portainer

  stop:
  - docker stop portainer

  remove:
  - docker rm -f portainer

  remove-volume:
  - docker volume rm portainer_data