version: 3

tasks:
  install:ct:
    cmds:
    - >
      curl -L https://github.com/flatcar/container-linux-config-transpiler/releases/download/v0.9.3/ct-v0.9.3-x86_64-unknown-linux-gnu
      -o /tmp/ct
    - chmod u+x /tmp/ct
    - sudo mv /tmp/ct /usr/bin/ct
    status:
    - command -v ct

  transform:docker:
    cmds:
    - cat config.yaml | docker run --rm -i ghcr.io/flatcar/ct:latest --platform=custom --pretty >> ignition.json
    - cp ignition.json ~/Public/
  
