version: 3

vars:
   # -- Available installers: nala | apt | brew?
  INSTALLER: nala

includes:
  diagrams: ./diagrams/Taskfile.yaml

tasks:
  default: 
  - task: list

  list:
    task --list-all | grep tools | grep ":install"

  install:essentials:
  - task: baobab:install
  # - task: install:stormssh
  - task: install:sops
  - task: install:age
  - task: install:direnv
  - task: install:pass
  - task: install:yq
  - task: install:tldr
  - task: install:gum
  - task: install:bat
  - task: install:cowsay

  install:cowsay:
    cmds:
    - cmd: sudo {{ .INSTALLER }} install -y cowsay
      platforms:
        - linux
    - cmd: brew install cowsay
      platforms:
        - darwin
    status:
    - command -v cowsay

  install:bat:
    cmds:
    - brew install bat
    status:
    - command -v bat

  install:gum:
    cmds:
    - brew install gum
    status:
    - command -v gum
  
  install:tldr:
    cmds:
    - sudo {{ .INSTALLER }} install -y tldr
    - tldr -u
    status:
    - command -v tldr

  install:desktop:
  - task: install:stacer
  - task: install:variety

  install:lazygit:
    cmds:
    - brew install lazygit
    status:
    - command -v lazygit


  arkade:install:
    cmds:
    - curl -sLS https://get.arkade.dev | sudo sh
    status:
    - command -v arkade

  pip:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y pip
    status:
    - command -v pip

  baobab:install:
    cmds:
    - sudo  {{ .INSTALLER }} install -y baobab
    status:
    - command -v baobab

  install:stormssh:
    deps:
    - pip:install
    cmds:
    - pip install stormssh
    status:
    - command -v stormssh

  stormssh:ui:
  - storm web 8080

  install:sops:
    deps:
    - arkade:install
    cmds:
    - arkade get sops
    status:
    - command -v sops

  install:age:
    cmds:
    - sudo  {{ .INSTALLER }} install age -y
    status:
    - command -v age

  age:create-key:
    cmds:
    - age-keygen -o ${HOME}/.age
    status:
    - test -f ${HOME}/.age

  install:direnv:
    cmds:
    - sudo  {{ .INSTALLER }} install direnv -y
    status:
    - command -v direnv

  install:pass:
    cmds:
    - sudo  {{ .INSTALLER }} install -y pass
    status:
    - command -v pass

  pass:init:
    cmds:
    - pass init {{ .CLI_ARGS }}
    status:
    - test -d ${HOME}/.password-store
    preconditions:
    - ARGS={{ .CLI_ARGS}}; echo ${ARGS?}

  gpg:generate-key:
    cmds:
    - gpg --gen-key

  install:variety:
    cmds:
    - sudo {{ .INSTALLER }} install variety -y
    #- task: variety:fix
    desc: Variety is automatic wallpaper changer
    status:
    - command -v variety

  variety:fix:
    cmds:
    - sed -i '/^# Gnome 3, Unity*/a gsettings set org.gnome.desktop.background picture-uri-dark "file://$WP" 2> /dev/null' /home/$USER/.config/variety/scripts/set_wallpaper

  neofetch:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y neofetch
    desc: Neofetch displays system information 

  cockpit:install:
    cmds:
    - sudo {{ .INSTALLER }} install -y cockpit
    - systemctl enable cockpit
    - systemctl start cockpit # port 9090
    desc: Cockpit is a Web UI OS manager

  install:stacer:
    cmds:
    - sudo {{ .INSTALLER }} install -y stacer
    desc: Stacer is a Linux monitoring tools with nice UI
    status:
    - command -v stacer

  gnome-shell-extensions:install:
  - sudo {{ .INSTALLER }} install gnome-shell-extensions -y
  - sudo {{ .INSTALLER }} install chrome-gnome-shell -y

  flatpack:
  - sudo {{ .INSTALLER }} install flatpak -y
  - sudo {{ .INSTALLER }} install gnome-software-plugin-flatpak -y
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  xclip:
  - sudo {{ .INSTALLER }}install xclip -y

  apache-utils:
  - sudo a{{ .INSTALLER }} install apache2-utils -y

  rich:install:
    desc: Install rick-cli
    deps:
    - pip:install
    cmds:
    - pip install rich-cli

  nodejs:install:
    cmds:
    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    - sudo {{ .INSTALLER }} update
    - sudo {{ .INSTALLER }} install nodejs -y
    - node -v
    - sudo npm install -g npm
  
  git-conventional-commits:install:
    deps:
    - install:nodejs
    cmds:
    - sudo npm install --global git-conventional-commits

  git-conventional-commits:init:
    cmds:
    - git-conventional-commits init

  dialog:install:
    desc: Install dialog
    cmds:
    - sudo {{ .INSTALLER }} install dialog -y

  install:yq:
    desc: Install yq
    env:
      BINARY: yq_linux_amd64
      VERSION: v4.24.2 
    cmds:
    - sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
    - sudo chmod +x /usr/bin/yq
    status:
    - command -v yq
