version: 3

tasks:
  copy:all:
  - task: copy:aliases
  - task: copy:env

  copy:aliases:
    cmds:
    - cp .aliases ~/.aliases
    sources:
    - .aliases

  copy:env:
    cmds:
    - cp .env ~/.env
    sources:
    - .env