version: 3

tasks:
  cockpit:install:
    cmds:
    - sudo apt-get install cockpit -y
    - sudo systemctl enable --now cockpit.socket
    - sudo ufw allow 9090
    status:
    - systemctl is-active cockpit.socket

  cockpit:podman:
    cmds:
    - sudo apt-get install podman cockpit-podman -y
    - sudo systemctl enable --now podman
    status:
    - command -v podman

