version: 3

# GOPASS IS NOT WORKING ON UBUNTU!

tasks:
  install:gopass:
    cmds:
    - wget https://github.com/gopasspw/gopass/releases/download/v1.15.5/gopass_1.15.5_linux_amd64.deb
    - sudo dpkg -i gopass_1.15.5_linux_amd64.deb
    - defer: rm gopass_1.15.5_linux_amd64.deb
    # - curl https://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg | sudo tee /usr/share/keyrings/gopass-archive-keyring.gpg
    # - |
    #   cat << EOF | sudo tee /etc/apt/sources.list.d/gopass.sources
    #   Types: deb
    #   URIs: https://packages.gopass.pw/repos/gopass
    #   Suites: stable
    #   Architectures: amd64 arm64 armhf
    #   Components: main
    #   Signed-By: /usr/share/keyrings/gopass-archive-keyring.gpg
    #   EOF
    # - sudo nala install -y gopass
    # - brew install gopass
    status:
    - command -v gopass


  gopass:setup:
    cmds:
    - gopass setup --crypto age
