
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    # security_opt:
    #  - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /run/podman/podman.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000

volumes:
  data: