version: 3

tasks:
  install:notion:
    cmds:
    - sudo snap install notion-snap
    status:
    - command -v notion-snap

  install:openshot:
  - sudo add-apt-repository ppa:openshot.developers/ppa
  - sudo nala install openshot-qt python3-openshot