service:
  hashicorp/vault:
    type: github
    url: hashicorp/vault
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    web_url: https://github.com/hashicorp/vault/releases/v{{ version }}
    icon: https://raw.githubusercontent.com/hashicorp/vault/main/ui/public/vault-logo.svg
  louislam/uptime-kuma:
    type: github
    url: louislam/uptime-kuma
    web_url: https://github.com/louislam/uptime-kuma/releases/{{ version }}
    icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
