version: '3'

tasks:
  configure:
    cmds:
    - git config --global credential.helper store
    - git config --global user.email "krzwiatrzyk@protonmail.com"
    - git config --global user.name "Krzysztof Wiatrzyk"
    status:
    - git config --list | grep krzwiatrzyk

  configure:hooks:
    desc: "Configure git hooks"
    cmds:
      - git config core.hooksPath '.git-hooks'
    
  commit:
    cmds:
    - task: add
    - |
      read -p "Enter type (feat,fix,docs): " TYPE
      read -p "Enter scope (i.e. flux): " SCOPE
      read -p "Enter subject (i.e. add test case): " SUBJECT
      git commit -m "${TYPE}(${SCOPE}): ${SUBJECT}"
    - task: push

  commit:fast:
    desc: Fast commit, I am lazy
    cmds:
    - task: add
    - |
      DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      git commit -m "feat(fast): ${DATE}" || echo
    - task: push

  add: git add . 
  push: git push origin main || echo

  fix: 
  - find .git/objects/ -size 0 -delete 
  - git fetch

  pull:
  - task: fix
  - git pull

  copy:scripts:
    cmds:
    - cmd: mkdir ~/.scripts
      ignore_error: true
    - cp scripts/fix-git.sh ~/.scripts