version: 3

tasks:
  install-all:
  - task: install
  - task: set-as-default-shell
  - task: oh-my-zsh:install
  - task: powerlevel10k:install
  - task: autosuggestions:install
  - task: fuzzy-finder:install
  - task: syntax-highlighting:install
  - task: :dotfiles:copy:zshrc
  - task: :dotfiles:copy:p10k

  install:
    cmds:
    - sudo apt-get install zsh -y
    status:
    - command -v zsh

  set-as-default-shell:
    cmds:
    - sudo chsh -s $(which zsh) $(whoami)
    status:
    - cat /etc/passwd | grep ${USER} | cut -d ":" -f 7 | grep zsh

  oh-my-zsh:install:
    cmds:
    - sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
    status:
    - test -d /home/${USER}/.oh-my-zsh
    interactive: true

  powerlevel10k:install:
    cmds:
    - sudo apt-get install fonts-font-awesome -y 
    - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    status:
    - test -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

  autosuggestions:install:
    cmds:
    - git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    status:
    - test -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

  syntax-highlighting:install:
    cmds:
    - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    status:
    - test -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

  fuzzy-finder:install:
    dir: ~/.oh-my-zsh/custom/plugins
    cmds:
    - git clone https://github.com/unixorn/fzf-zsh-plugin.git fzf-zsh-plugin
    status:
    - test -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin

  fix-history:
    cmds:
    - |
      cd ~
      mv .zsh_history .zsh_history_bad
      strings -eS .zsh_history_bad > .zsh_history
      zsh -c "fc -R .zsh_history"
