version: 3

tasks:
  install:smartmontools:
  - sudo apt-get install smartmontools -y

  check-smart-capability-for-drive:
    desc: |
      Example: sudo smartctl -i /dev/sda 
    cmds:
    - sudo smartctl -i {{ .CLI_ARGS }} 

  list-discs:
  - lsblk

  run: |
   docker run -it --rm -p 8080:8080 -p 8086:8086 \
    -v `pwd`/scrutiny:/opt/scrutiny/config \
    -v `pwd`/influxdb2:/opt/scrutiny/influxdb \
    -v /run/udev:/run/udev:ro \
    --cap-add SYS_RAWIO \
    --device=/dev/sda \
    --device=/dev/sdb \
    --name scrutiny \
    ghcr.io/analogj/scrutiny:master-omnibus