version: 3

tasks:
  install:
    cmds:
    - curl -s https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] http://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
    - sudo apt update
    - sudo apt install kopia
    - sudo apt install kopia-ui
    status:
    - command -v kopia-ui

