version: 3

tasks:
  stormssh:install:
  - pip install stormssh

  stormssh:ui:
  - storm web 8080

  sops:install:
  - arkade get sops

  age:install:
  - sudo apt install age -y

  age:create-key:
    cmds:
    - age-keygen -o ${HOME}/.age
    status:
    - test -f ${HOME}/.age

  direnv:install:
  - sudo apt install direnv -y

  pass:install:
    cmds:
    - sudo apt-get install -y pass
    status:
    - command -v pass

  pass:init:
    cmds:
    - pass init {{ .CLI_ARGS }}
    status:
    - test -d ${HOME}/.password-store
    preconditions:
    - ARGS={{ .CLI_ARGS}}; echo ${ARGS?}

  gpg:generate-key:
    cmds:
    - gpg --gen-key