version: 3

tasks:
  ntfy:ssh:
    cmds:
    - cp ntfy-ssh-login.sh /usr/bin/ntfy-ssh-login.sh
    - cp sshd.conf /etc/pam.d/sshd
    sources:
    - ntfy-ssh-login.sh
    - sshd.conf
    generates:
      - /etc/pam.d/sshd
      - /usr/bin/ntfy-ssh-login.sh